// Autogenerated from Pigeon (v17.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by SYFlutterFaceVerifyHostApi.
NSObject<FlutterMessageCodec> *SYFlutterFaceVerifyHostApiGetCodec(void);

@protocol SYFlutterFaceVerifyHostApi
/// 初始化SDK
- (void)initServiceWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 开始验证
- (void)verifyCertifyId:(NSString *)certifyId completion:(void (^)(NSDictionary *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpSYFlutterFaceVerifyHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SYFlutterFaceVerifyHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
